export const sensorTypes = {
    HUM_SUELO_H: "HUM_SUELO_H",
    HUM_SUELO_M: "HUM_SUELO_M",
    HUM_SUELO_L: "HUM_SUELO_L",
    HUM_AMBIENTE: "HUM_AMBIENTE",
    TEMP_AMBIENTE: "TEMP_AMBIENTE",
    LLUVIA: "LLUVIA",
    LUZ: "LUZ",
};
